import { jsPDF } from "jspdf";
import type { InvoiceMeta, LineItemRow } from "../data/InvoiceDatabase";

function fmt(paise: number | null): string {
  if (paise == null) return "—";
  return `Rs. ${(paise / 100).toFixed(2)}`;
}

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso);
  return isNaN(d.getTime()) ? iso : d.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

export function generateInvoicePdf(inv: InvoiceMeta, lineItems: LineItemRow[]): ArrayBuffer {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const margin = 18;
  const colRight = W - margin;
  let y = 20;

  const text  = (str: string, x: number, size = 10, style: "normal" | "bold" = "normal") => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.text(str, x, y);
  };
  const line  = () => { doc.setDrawColor(220); doc.line(margin, y, colRight, y); y += 1; };
  const gap   = (mm = 5) => { y += mm; };

  // Header
  text("jInvoice", margin, 18, "bold");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text("Extracted invoice record", margin, y + 5);
  doc.setTextColor(0);

  doc.setFontSize(10);
  doc.text(`Exported: ${new Date().toLocaleDateString("en-IN")}`, colRight, y, { align: "right" });
  y += 14;
  line(); gap(5);

  // Merchant block
  text(inv.merchantName ?? "Unknown merchant", margin, 14, "bold");
  gap(7);
  if (inv.merchantAddress) { text(inv.merchantAddress, margin, 9); gap(5); }
  if (inv.merchantGstin)   { text(`GSTIN: ${inv.merchantGstin}`, margin, 9); gap(5); }
  gap(3);

  // Key fields
  const pairs: [string, string][] = [
    ["Invoice Date",   fmtDate(inv.invoiceDate)],
    ["Grand Total",    fmt(inv.grandTotalPaise)],
    ["Tax",            fmt(inv.taxPaise)],
    ["Discount",       inv.discountPaise > 0 ? fmt(inv.discountPaise) : "—"],
    ["Payment Mode",   inv.paymentMode ?? "—"],
    ["Category",       inv.category?.replace(/_/g, " ") ?? "—"],
    ["Status",         inv.status],
    ["Source",         inv.importSource],
  ];
  line(); gap(5);
  for (const [label, value] of pairs) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 38, y);
    y += 6;
  }

  // Line items
  if (lineItems.length > 0) {
    gap(4); line(); gap(5);
    text("Line Items", margin, 11, "bold"); gap(7);

    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("Item", margin, y);
    doc.text("Qty", margin + 90, y, { align: "right" });
    doc.text("Unit Price", margin + 122, y, { align: "right" });
    doc.text("Total", colRight, y, { align: "right" });
    gap(5);
    doc.setDrawColor(180);
    doc.line(margin, y, colRight, y);
    gap(4);

    doc.setFont("helvetica", "normal");
    for (const item of lineItems) {
      doc.text(doc.splitTextToSize(item.name, 85)[0], margin, y);
      doc.text(String(item.quantity),                      margin + 90,  y, { align: "right" });
      doc.text(fmt(item.unitPricePaise),                   margin + 122, y, { align: "right" });
      doc.text(fmt(item.totalPricePaise),                  colRight,     y, { align: "right" });
      y += 6;
      if (y > 270) { doc.addPage(); y = 20; }
    }

    // totals footer
    gap(2); doc.setDrawColor(180); doc.line(margin + 88, y, colRight, y); gap(5);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("Grand Total", margin + 122, y, { align: "right" });
    doc.text(fmt(inv.grandTotalPaise), colRight, y, { align: "right" });
    gap(8);
  }

  // Footer
  y = 285;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(150);
  doc.text("Generated by jInvoice — all data extracted on-device, nothing shared.", margin, y);

  return doc.output("arraybuffer") as ArrayBuffer;
}

export function invoicePdfFilename(inv: InvoiceMeta): string {
  if (inv.sourceFilename) {
    return inv.sourceFilename.toLowerCase().endsWith(".pdf")
      ? inv.sourceFilename
      : `${inv.sourceFilename}.pdf`;
  }
  const merchant = (inv.merchantName ?? "Unknown")
    .replace(/[^a-z0-9]+/gi, "_")
    .replace(/^_|_$/g, "")
    .toLowerCase();
  const date = inv.invoiceDate ?? "unknown";
  return `Invoice_${merchant}_${date}.pdf`;
}
