/**
 * Reads credentials from .env and writes electron/credentials.mjs
 * so they get baked into the packaged app at build time.
 * Run automatically by `preelectron:build`.
 */
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const env = {};
try {
  for (const line of readFileSync(join(root, ".env"), "utf8").split("\n")) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)\s*=\s*(.+?)(\s*#.*)?$/);
    if (m) env[m[1]] = m[2].replace(/^["']|["']$/g, "").trim();
  }
} catch {
  console.warn("No .env found — credentials will be empty. Set them before building.");
}

const creds = {
  GOOGLE_CLIENT_ID:     env.GOOGLE_CLIENT_ID     ?? "",
  GOOGLE_CLIENT_SECRET: env.GOOGLE_CLIENT_SECRET  ?? "",
  AZURE_CLIENT_ID:      env.AZURE_CLIENT_ID       ?? "",
  AZURE_CLIENT_SECRET:  env.AZURE_CLIENT_SECRET   ?? "",
};

writeFileSync(
  join(root, "electron", "credentials.mjs"),
  `// Auto-generated by prebuild.mjs — do not commit\nexport const credentials = ${JSON.stringify(creds, null, 2)};\n`,
);

console.log("electron/credentials.mjs written.");
